export const errorCodes = {
    BRANCH_IS_EXISTED: { code: "BRANCH_IS_EXISTED", message: "Tên chi nhánh đã tồn tại!" },
    GRADE_CODE_EXISTED: { code: "GRADE_CODE_EXISTED", message: "Mã khối lớp đã được sử dụng." },
    SUBJECT_NAME_EXISTED: { code: "SUBJECT_NAME_EXISTED", message: "Môn học đã được sử dụng" },
    CLASSROOM_CODE_EXISTED: { code: "CLASSROOM_CODE_EXISTED", message: "Mã lớp đã được sử dụng" },
    CLASSROOM_NAME_EXISTED: { code: "CLASSROOM_NAME_EXISTED", message: "Tên lớp học đã được sử dụng" },
    SCHOOL_YEAR_IS_GOING_ON: { code: "SCHOOL_YEAR_IS_GOING_ON", message: "Đã có năm học đang diễn ra!" },
    CLASSROOM_STUDENT_ALREADY_EXISTS: { code: "CLASSROOM_STUDENT_ALREADY_EXISTS", message: "Học sinh đã có lớp!" },
    STUDENT_NOT_HAS_STUDENT_ROLE: { code: "STUDENT_NOT_HAS_STUDENT_ROLE" },
    USER_NOT_EXIST_IN_CURRENT_SCHOOL: { code: "USER_NOT_EXIST_IN_CURRENT_SCHOOL" },
    USER_NOT_ACTIVE: { code: "USER_NOT_ACTIVE", message: "Học sinh đang ở trạng thái ngừng hoạt động" },
    HOLIDAY_OVERLAP :{ code : "HOLIDAY_OVERLAP" , message : "Khoảng thời gian này đang diễn ra ngày lễ khác" },
    USER_CODE_IS_EXISTED: { code: "USER_CODE_IS_EXISTED", message: "Mã người dùng đã được sử dụng!", field: "code" },
    USER_PHONE_IS_EXISTED: { code: "USER_PHONE_IS_EXISTED", message: "Số điện thoại đã được sử dụng!", field: "phone" },
    USER_EMAIL_IS_EXISTED: { code: "USER_EMAIL_IS_EXISTED", message: "Email đã được sử dụng!", field: "email" },
    SCHOOL_YEAR_ENDED: { code: "SCHOOL_YEAR_ENDED", message: "Năm học đã kết thúc" },
    USER_LIMIT_REACHED: { code: "USER_LIMIT_REACHED", message: "Số lượng người dùng của hệ thống đã đạt đến giới hạn tối đa" },
    FILE_NAME_EXISTED: { code: "FILE_NAME_EXISTED", message: "Tệp [file] đã tồn tại" , subMessage:'Tiêu đề đã tồn tại', mutiErrorMessage:'Những tệp [file] đã tồn tại' },
    FILE_CONTENT_TYPE_NOT_ALLOWED: { code: "FILE_CONTENT_TYPE_NOT_ALLOWED", message: "Tệp [file] không hợp lệ. File cần thuộc một trong các định dạng: .ppt, .doc, .docx, .xls, .xlsx, .jpg, .png, .jpeg, .pdf, .zip, .rar, .mp3, .mp4" },
    DUPLICATE_SUBJECT_FINAL_SCORE: { code: "DUPLICATE_SUBJECT_FINAL_SCORE", message: "Môn học đã có công thức điểm khác ở niên khóa!" },
    MAX_FILE_SIZE: { code: "MAX_FILE_SIZE", message: "Tài liệu cần có dung lượng ≤ 100MB" },
    FOLDER_RESOURCE_EXISTED: { code: "FOLDER_RESOURCE_EXISTED", message: "Thư mục đã tồn tại" },
    FILE_UPLOAD_ERROR: { code: "FILE_UPLOAD_ERROR", message: "Một số file không hợp lệ [file]"  },
};
