export const branchData = [
    {
        code: "CN001",
        name: "Chi nhánh A",
        phone: "0123456789",
        address: "Số 123, Đường ABC",
        ward: "Phường X",
        district: "Quận Y",
        city: "Thành phố Z",
    },
    {
        code: "CN002",
        name: "Chi nhánh B",
        phone: "0987654321",
        address: "Số 456, Đường XYZ",
        ward: "Phường M",
        district: "Quận N",
        city: "Thành phố P",
    },
    {
        code: "CN003",
        name: "Chi nhánh C",
        phone: "0123456789",
        address: "Số 789, Đường DEF",
        ward: "Phường A",
        district: "Quận B",
        city: "Thành phố C",
    },
    {
        code: "CN004",
        name: "Chi nhánh D",
        phone: "0987654321",
        address: "Số 987, Đường UVW",
        ward: "Phường G",
        district: "Quận H",
        city: "Thành phố I",
    },
    {
        code: "CN005",
        name: "Chi nhánh E",
        phone: "0123456789",
        address: "Số 654, Đường JKL",
        ward: "Phường Q",
        district: "Quận R",
        city: "Thành phố S",
    },
    {
        code: "CN006",
        name: "Chi nhánh F",
        phone: "0987654321",
        address: "Số 321, Đường MNO",
        ward: "Phường T",
        district: "Quận U",
        city: "Thành phố V",
    },
    {
        code: "CN007",
        name: "Chi nhánh G",
        phone: "0123456789",
        address: "Số 135, Đường PQR",
        ward: "Phường W",
        district: "Quận X",
        city: "Thành phố Y",
    },
    {
        code: "CN008",
        name: "Chi nhánh H",
        phone: "0987654321",
        address: "Số 531, Đường STU",
        ward: "Phường Z",
        district: "Quận AA",
        city: "Thành phố BB",
    },
    {
        code: "CN009",
        name: "Chi nhánh I",
        phone: "0123456789",
        address: "Số 246, Đường VWX",
        ward: "Phường CC",
        district: "Quận DD",
        city: "Thành phố EE",
    },
    {
        code: "CN010",
        name: "Chi nhánh J",
        phone: "0987654321",
        address: "Số 864, Đường YZA",
        ward: "Phường FF",
        district: "Quận GG",
        city: "Thành phố HH",
    },
];
